#! /usr/bin/python
# coding: utf-8

import os
import sys
from optparse import OptionParser
import aojtools

def convert(s):
    for enc in ['utf-8', 'cp932', 'sjis', 'euc-jp', 'iso-2022-jp']:
        try:
           t = s.decode(enc)
           return t.encode(aojtools.settings.SITEENCODING)
        except Exception, e:
            pass
    raise Exception('unknown file encoding.')

def main():
    filepath = ''
    lang = ''
    problem_id = ''
    user_id = ''
    password = ''
    
    parser = OptionParser()
    parser.add_option('-p', '--password', dest='pwd', metavar='PASSWORD')
    parser.add_option('-u', '--userid', dest='uid', metavar='USERID')
    parser.add_option('-l', '--language', dest='lang', metavar='LANGUAGE', help='c,cpp,java')
    
    opts, args = parser.parse_args()
    
    print parser.pwd
    print parser.uid
    print parser.lang
    
    if lang = '':
        ext = '.c'
        pairs = [('.c', api.settings.LANG_C), ('.cpp.cxx.cc.cp', api.settings.LANG_CPP), ('.java', api.settings.LANG_JAVA)]
        for exts, cst in pairs:
            if ext in exts:
                lang = cst
    
    info = {
        'user_id': user_id,
        'password': password,
        'code': convert(open(filepath).read()),
        'problem_id': problem_id,
        'lang': lang
    }
    try:
        status = aojtools.submit()
        print status.status
    except Exception, e:
        print '******************** ERROR *********************'
        print e

if __name__ == '__main__':
    main()
